
// Generated by https://jvilk.com/MakeTypes/ on the fixture API response from
// https://gitlab.com/gitlab-org/gitlab/blob/master/doc/api/pipelines.md
export interface Pipeline {
  id: number;
  status: string;
  ref: string;
  sha: string;
  before_sha: string;
  tag: boolean;
  yaml_errors?: null;
  user: User;
  created_at: string;
  updated_at: string;
  started_at?: null;
  finished_at: string;
  committed_at?: null;
  duration?: null;
  coverage: string;
  web_url: string;
}
interface User {
  name: string;
  username: string;
  id: number;
  state: string;
  avatar_url: string;
  web_url: string;
}
